export default (() => [
{ quote: 'With self-discipline most anything is possible.',
  author: 'Theodore Roosevelt' },
{ quote: 'I look back on my life like a good day\'s work, it was done and I am satisfied with it.',
  author: 'Grandma Moses' },
{ quote: 'I certainly hope I\'m not still answering child-star questions by the time I reach menopause.',
  author: 'Christina Ricci' },
{ quote: 'There\'s a consistency in my work that pops up independent of the limitations of the technology.',
  author: 'Douglas Trumbull' },
{ quote: 'Vegetarians are cool. All I eat are vegetarians - except for the occasional mountain lion steak.',
  author: 'Ted Nugent' },
{ quote: 'The enemy of society is middle class and the enemy of life is middle age.',
  author: 'Orson Welles' },
{ quote: 'Everything takes me longer than I expect. It\'s the sad truth about life.',
  author: 'Donna Tartt' },
{ quote: 'A reporter\'s ability to keep the bond of confidentiality often enables him to learn the hidden or secret aspects of government.',
  author: 'Bob Woodward' },
{ quote: 'If you want a vision of the future, imagine a boot stamping on a human face - forever.',
  author: 'George Orwell' },
{ quote: 'Maybe I\'ll be a feminist in my old age.',
  author: 'Bjork' },
{ quote: 'Education should prepare our minds to use its own powers of reason and conception rather than filling it with the accumulated misconceptions of the past.',
  author: 'Bryant H. McGill' },
{ quote: 'Maybe the body learns from dreams. Maybe the muscles, the neutrons, revitalize.',
  author: 'Michael Zaslow' },
{ quote: 'I do not recall a Jewish home without a book on the table.',
  author: 'Elie Wiesel' },
{ quote: 'Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.',
  author: 'Henry Van Dyke' },
{ quote: 'When I was in college, I was debating to try my hand at show business, or to become a professor. I just thought of the risk of not going into show business and always wondering if I would\'ve had a chance. Because that\'s where my real heart was.',
  author: 'Steve Martin' },
{ quote: 'I\'ll love you, dear, I\'ll love you till China and Africa meet and the river jumps over the mountain and the salmon sing in the street.',
  author: 'W. H. Auden' },
{ quote: 'I have a lot of money stashed away, but I do live my life from day to day.',
  author: 'Elton John' },
{ quote: 'Look, I\'m very much in favor of tax cuts, but not with borrowed money. And the problem that we\'ve gotten into in recent years is spending programs with borrowed money, tax cuts with borrowed money, and at the end of the day that proves disastrous. And my view is I don\'t think we can play subtle policy here.',
  author: 'Alan Greenspan' },
{ quote: 'You take somebody that cries their goddam eyes out over phoney stuff in the movies, and nine times out of ten they\'re mean bastards at heart.',
  author: 'J. D. Salinger' },
{ quote: 'All objects, all phases of culture are alive. They have voices. They speak of their history and interrelatedness. And they are all talking at once!',
  author: 'Camille Paglia' },
{ quote: 'An inventor is simply a fellow who doesn\'t take his education too seriously.',
  author: 'Charles Kettering' },
{ quote: 'If people choose to live their life in a way that does not confront the more troubling aspects of their experience, that\'s fine, if it works for them. But it will probably make them uncomfortable if they come up against somebody like me. So they just shouldn\'t! They shouldn\'t read my work!',
  author: 'Joyce Maynard' },
{ quote: 'Art is the signature of civilizations.',
  author: 'Beverly Sills' },
{ quote: 'A sculptor wields The chisel, and the stricken marble grows To beauty.',
  author: 'William C. Bryant' },
{ quote: 'Travel aesthetics should be just as comfortable and practical as they are fashionable.',
  author: 'Miguel Jontel Pimentel' },
{ quote: 'If you have learned how to disagree without being disagreeable, then you have discovered the secrete of getting along - whether it be business, family relations, or life itself.',
  author: 'Bernard Meltzer' },
{ quote: 'The principle of the Gothic architecture is infinity made imaginable.',
  author: 'Samuel Taylor Coleridge' },
{ quote: 'Courage easily finds its own eloquence.',
  author: 'Plautus' },
{ quote: 'Labor, under their current leadership, want to be the Downtown Abbey party when it comes to educational opportunity. They think working class children should stick to the station in life they were born into - they should be happy to be recognized for being good with their hands and not presume to get above themselves.',
  author: 'Michael Gove' },
{ quote: 'My mom said, \'Don\'t get married. You\'re too young. Go out there and experience what life has to offer.\' And I did.',
  author: 'Emmitt Smith' },
{ quote: 'In the forensic science course I took at university they used photographs of dead bodies. For ballistics they showed us a guy lying on the floor, and his head had burst.',
  author: 'Denise Mina' },
{ quote: 'The trouble with jogging is that the ice falls out of your glass.',
  author: 'Martin Mull' },
{ quote: 'A lot of people think I\'m that guy in \'Betsy\'s Wedding\', but I\'m not. What it is for me is that, on some level, I connect with the character emotionally.',
  author: 'Anthony LaPaglia' },
{ quote: 'Bureaucracy gives birth to itself and then expects maternity benefits.',
  author: 'Dale Dauten' },
{ quote: 'The amazing thing now is that most of those so-called critics who were telling me to find my own voice seem to have lost theirs.',
  author: 'Brian Lumley' },
{ quote: 'Genuine forgiveness does not deny anger but faces it head-on.',
  author: 'Alice Duer Miller' },
{ quote: 'Pessimism leads to weakness, optimism to power.',
  author: 'William James' },
{ quote: 'I\'d like to do a lot of things - whether in design or architecture or business.',
  author: 'Caroline Wozniacki' },
{ quote: '\'Therefore\' is a word the poet must not know.',
  author: 'Andre Gide' },
{ quote: 'I know there is a Supreme Being who rules the affairs of men and whose goodness and mercy have always followed the American people, and I know He will not turn from us now if we humbly and reverently seek His powerful aid.',
  author: 'Grover Cleveland' },
{ quote: 'Markets rebounded quickly from morning jitters after the London Thursday terrorist bombing.',
  author: 'Cliff Stearns' },
{ quote: 'Technology is making design more exciting, with color, wallpaper, textures, fabrics that could never have been created without the technology.',
  author: 'David Bromstad' },
{ quote: 'The South is very beautiful but its beauty makes one sad because the lives that people live here, and have lived here, are so ugly.',
  author: 'James Baldwin' },
{ quote: 'I want to see far more decisions taken far closer to the patients, the passengers and the pupils. Far more power for locally and regionally elected politicians who understand best the needs of their areas. And far more say too for the dedicated staff at all levels in health and education.',
  author: 'Charles Kennedy' },
{ quote: 'So one reason the science educators panic at the first sign of public rebellion is that they fear exposure of the implicit religious content in what they are teaching.',
  author: 'Phillip E. Johnson' },
{ quote: 'I was sent to a finishing school, which didn\'t last long when mother found out how badly chaperoned we were. Then I \'came out\' before going to a domestic science school.',
  author: 'Mary Wesley' },
{ quote: 'I tend to show everything I do to my family, to check they won\'t be offended.',
  author: 'David Sedaris' },
{ quote: 'Really I don\'t like human nature unless all candied over with art.',
  author: 'Virginia Woolf' },
{ quote: 'Controversy is part of the nature of art and creativity.',
  author: 'Yoko Ono' },
{ quote: 'It\'s a funny old world.',
  author: 'Margaret Thatcher' },
{ quote: 'Santa is our culture\'s only mythic figure truly believed in by a large percentage of the population. It\'s a fact that most of the true believers are under eight years old, and that\'s a pity.',
  author: 'Chris Van Allsburg' },
{ quote: 'Do not ever say that the desire to \'do good\' by force is a good motive. Neither power-lust nor stupidity are good motives.',
  author: 'Ayn Rand' },
{ quote: 'Love can sometimes be magic. But magic can sometimes... just be an illusion.',
  author: 'Javan' },
{ quote: 'I put the costume on and said \'It\'s not very comfortable, but it looks amazing,\' so it\'s all good.',
  author: 'Chris Hemsworth' },
{ quote: 'Solitude, though it may be silent as light, is like light, the mightiest of agencies for solitude is essential to man. All men come into this world alone and leave it alone.',
  author: 'Thomas de Quincey' },
{ quote: 'I would find myself laughing and wondering where these ideas came from. You can call it imagination, I suppose. But I was grateful for wherever they came from.',
  author: 'Amy Tan' },
{ quote: 'This truth is a remedy against spiritual pride, namely, that none should account himself better before God than others, though perhaps adorned with greater gifts, and endowments.',
  author: 'Johann Arndt' },
{ quote: 'I cannot say how strongly I object to people using other people\'s writing as research. Research is non-fiction, especially for horror, fantasy, science fiction. Do not take your research from other people\'s fiction. Just don\'t.',
  author: 'Laurell K. Hamilton' },
{ quote: 'It is cruel, you know, that music should be so beautiful. It has the beauty of loneliness of pain: of strength and freedom. The beauty of disappointment and never-satisfied love. The cruel beauty of nature and everlasting beauty of monotony.',
  author: 'Benjamin Britten' },
{ quote: 'Look, I want what\'s good for everybody. I want to promote good state education for all. I want to raise standards for all kids, irrespective of race and class but why can\'t they all just do what I say when I know I\'m right?',
  author: 'Arabella Weir' },
{ quote: 'Each underestimates her own power and overestimates the other\'s.',
  author: 'Deborah Tannen' },
{ quote: 'I was lucky enough when it came to sports and work ethic to be taught some basics that continue to be important.',
  author: 'Joe Namath' },
{ quote: 'I\'m actually not a big fan of the word hope. I think it\'s a depressing word. I don\'t want to hope - I want to know. Like I don\'t hope there\'s a God, I know there\'s a God.',
  author: 'Kelly Clarkson' },
{ quote: 'My parents have a wonderful marriage, for many years. But I can\'t commit myself for such a long time.',
  author: 'Kim Wilde' },
{ quote: 'We came from a family where we ran our own small business. Our dad made his own products. We made our own sausages, our own meatloafs, our own pickles. Dad had to do everything himself. He had to figure out how to finance his business.',
  author: 'Marcy Kaptur' },
{ quote: 'Above all, we must have great respect for these people who also suffer and who want to find their own way of correct living. On the other hand, to create a legal form of a kind of homosexual marriage, in reality, does not help these people.',
  author: 'Joseph Ratzinger' },
{ quote: 'The real 1960s began on the afternoon of November 22, 1963. It came to seem that Kennedy\'s murder opened some malign trap door in American culture, and the wild bats flapped out.',
  author: 'Lance Morrow' },
{ quote: 'Everybody\'s business is nobody\'s business, and nobody\'s business is my business.',
  author: 'Clara Barton' },
{ quote: 'I love Valentine\'s Day! I love it, I love it, I love it. I like having doors opened for me. My favorite romantic comedy is \'When Harry Met Sally.\'',
  author: 'Ginnifer Goodwin' },
{ quote: 'There was nothing more important I could do than be supportive as a dad.',
  author: 'Arne Duncan' },
{ quote: 'An order of government, established by such an all-wise, powerful being, must be good and perfect, and must be calculated to promote the permanent peace, happiness, and well-being of all his subjects.',
  author: 'Orson Pratt' },
{ quote: 'We can close the gap and improve what happens in the classroom by using educational technology that is the same high quality everywhere.',
  author: 'Major Owens' },
{ quote: 'If the choice is between doing something supercool and having no one hear it and doing something equally cool and tricking people into putting it on the radio, I don\'t think the second option is some big sellout.',
  author: 'Julian Casablancas' },
{ quote: 'Married love between man and woman is bigger than oaths guarded by right of nature.',
  author: 'Aeschylus' },
{ quote: 'I seek to call America home to those principles that gave us birth.',
  author: 'George McGovern' },
{ quote: 'Effective communication is 20% what you know and 80% how you feel about what you know.',
  author: 'Jim Rohn' },
{ quote: 'I am sometimes a fox and sometimes a lion. The whole secret of government lies in knowing when to be the one or the other.',
  author: 'Napoleon Bonaparte' },
{ quote: 'I\'m a feminist, but I think that romance has been taken away a bit for my generation. I think what people connect with in novels is this idea of an overpowering, encompassing love - and it being more important and special than anything and everything else.',
  author: 'Emma Watson' },
{ quote: 'Freedom in a commons brings ruin to all.',
  author: 'Garrett Hardin' },
{ quote: 'One of the lessons of history is that nothing is often a good thing to do and always a clever thing to say.',
  author: 'Will Durant' },
{ quote: 'Divorced men are more likely to meet their car payments than their child support obligations.',
  author: 'Susan Faludi' },
{ quote: 'Car designers are just going to have to come up with an automobile that outlasts the payments.',
  author: 'Erma Bombeck' },
{ quote: 'I went to a football school, which meant that I went to a university that served up education and was simultaneously operating a sports franchise.',
  author: 'Susan Orlean' },
{ quote: 'I think my first album opened a lot of doors for me to push the freedom of speech to the limit.',
  author: 'Eminem' },
{ quote: 'A Latin teacher told me I might make a good actress, and that stuck in my memory. I did some modeling, and Polanski gave me that small part.',
  author: 'Jacqueline Bisset' },
{ quote: 'In this situation I was constantly exposed to danger and death.',
  author: 'Daniel Boone' },
{ quote: 'We looked at each other standing on the podium, and I think we all were tearing up. But we had to keep it cool. I think we did. Then we let out a breath.',
  author: 'Michael Irvin' },
{ quote: 'Anybody under the age of forty knows hip-hop, gospel and R&ampB pretty well, and it\'s all a part of what we consider to be \'black music.\' There is a natural synergy between the three.',
  author: 'John Legend' },
{ quote: 'Never be afraid to meet to the hilt the demand of either work, or friendship - two of life\'s major assets.',
  author: 'Eleanor Robson Belmont' },
{ quote: 'If your movies don\'t perform, they just stop calling you.',
  author: 'Matt Damon' },
{ quote: 'Reflect upon your present blessings of which every man has many - not on your past misfortunes, of which all men have some.',
  author: 'Charles Dickens' },
{ quote: 'I attach the greatest importance to an amplification of the peace efforts in the Middle East. I would also like to see a greater dialogue between the U.S. and the EU.',
  author: 'Francois Hollande' },
{ quote: 'The best of us must sometimes eat our words.',
  author: 'J. K. Rowling' },
{ quote: 'You cannot, in human experience, rush into the light. You have to go through the twilight into the broadening day before the noon comes and the full sun is upon the landscape.',
  author: 'Woodrow Wilson' },
{ quote: 'There is no worse screen to block out the Spirit than confidence in our own intelligence.',
  author: 'John Calvin' },
{ quote: 'I\'ve got a very deep and abiding passion about education being far more than buildings and textbooks it\'s what children bring into school with them.',
  author: 'Johann Lamont' },
{ quote: 'I don\'t care half so much about making money as I do about making my point, and coming out ahead.',
  author: 'Cornelius Vanderbilt' },
{ quote: 'I didn\'t feel any remorse or sympathy if I injured a rival. I went over the top a few times but I never broke anyone\'s leg.',
  author: 'Peter Storey' },
{ quote: 'When the fabric of society is so rigid that it cannot change quickly enough, adjustments are achieved by social unrest and revolutions.',
  author: 'John Boyd Orr' },
{ quote: 'Sometimes you ask God for something and you don\'t know what you\'re asking.',
  author: 'Mahalia Jackson' }
])()
