export default (() => [
    "Every pixel must be correct",
    "Creative for sure, but as Einstein says \"Creativity is hidden mechanisms\"",
    "Simple stuff its all about aesthetics and compatibility",
    "All very comprehensible, complex beyond our understanding?\nAbsolutely not",
    "Its comprehensible",
    "Remember WWJD - What Would Jobs Do",
    "Functionality is assumed by the consumer",
    "Somewhat encoded ie unreadable",
    "Look at the actual html, nothing complicated",
    "Definitely took effort but nothing beyond comprehension",
    "You're right its not school so you didn't actually learn anything worth value",
    "Formal education and education, one people believe the other people recieve",
    "What seems so valueless and effortless to someone who has spent 100s of hours learning is not valueless and effortless to people who have 0",
    "Is this The Odin Project or not",
    "You actually want to make money you have to put effort in",
    "I pick up incredibly fast and I have to",
    "I'm the fuckin point of contact",
    "I think it's inarguable to anyone experienced that 15% for literally creating the business is nothing",
    "Just pick up the phone and see what its like on this end",
    "Nothings in stone",
    "I can walk if no one can rise to the occasion",
    "Its not lying so long as I don't promise specifics",
    "Just charge him a pretty penny",
    "Who knows just how much this rich real estate fuck is willing to pay for basic ish",
    "Don't talk to me like I'm an expert",
    "We have no obligations to this person",
    "But guess what, the more work its gonna take, obviously the more money we can get from it",
    "Its me thats takin the fuckin fall its me thats dealing with the guy you guys just sit back and contribute if its convenient for you, you aren't liable whatsoever",
    "This seems to be a hot industry, first contact he's already interested in talking",
    "Told him I would check with my \"team\" to see what we could \"do\"",
    "You can have all the talent in the world but its nearly nothing if you can't sell",
    "It would be incredible if you guys understood this core sales principle in a matter of minutes",
    "Wipe the idea that a \"CEO\", of even the top companies of the world, knows \"everything\"",
    "When I'm talking to you guys I don't feel the same level of pressure to quickly demonstrate my competence as I do when I'm talking to a CEO",
    "My meaning keeps being misinterpreted by fault of the mechanism by which we are communicating",
    "Can't be too \"soft\" can't be too \"hard\", be just right and you blend",
    "It's the coffee bean concept in sales: When you boil an egg it gets too hard, when you boil a noodle it gets too soft, when you boil a coffee bean it makes coffee. Moral of the story, don't be too hard on people, don't be too soft on people, be just right and people will be like you",
    "Pay obviously, but consistent pay idk. At worst it's project experience",
    "If y'all aren't interested I'm gonna go flip cars",
    "I need to know that I have something behind me when I call these people",
    "I know how to sell, I know sales and marketing and other business principles. You guys might know how to put together a functional website, nothing fancy",
    "There exists, here, on this rock we call Earth, business owners who don't have the slightest clue as to how to get a website going and they don't want to pay a big web dev company 10-50 k, we find those people who just want SOMETHING and give them just that",
    "If they show interest thats a win",
    "I sold on day one",
    "That's called an objection",
    "Control the sale",
    "Always remember it boils down to get and post requests",
    "There are a lot of businesses out there gentlemen",
    "One thing I learned from doing business to business sales is that business owners rarely know anything outside of the service they provide",
    "The underlying concept that we just have to remember, people don't have a website, we have the capacity to build a website",
    "RESTful - Its not complicated",
    "Not an easy job selling shit",
    "I'm better when I'm talking to someone who isn't already convinced they want nothing to do with me"
])()
